services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: srebootcamp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ../..
    container_name: sre-api

    depends_on:
      - postgres

    environment:
      PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: srebootcamp

    ports:
      - "8080:8080"

volumes:
  postgres-data: