apiVersion: apps/v1
kind: Deployment

metadata:
  name: sre-api
  namespace: sre-bootcamp

spec:
  replicas: 2

  selector:
    matchLabels:
      app: sre-api

  template:
    metadata:
      labels:
        app: sre-api

    spec:
      containers:
        - name: api

          image: sre-bootcamp-api:v4

          imagePullPolicy: Never

          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: api-config

            - secretRef:
                name: api-secret